// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: pkg/apis/v1alpha1/ax.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObjectMeta is metadata for AX resources.
type ObjectMeta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Atespace          string                 `protobuf:"bytes,2,opt,name=atespace,proto3" json:"atespace,omitempty"`
	CreationTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *ObjectMeta) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *ObjectMeta            `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *TaskSpec              `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *TaskStatus            `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Task) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Task) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Task) GetSpec() *TaskSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Task) GetStatus() *TaskStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type TaskSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Suspend   bool                   `protobuf:"varint,2,opt,name=suspend,proto3" json:"suspend,omitempty"`
	Image     string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Command   []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Env       []*EnvVar              `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty"`
	Resources *ResourceReqs          `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	// workspaces binds one or more Workspaces, each mounted at its own path
	// under /workspace. The first entry is the task command's working directory.
	Workspaces []*WorkspaceRef `protobuf:"bytes,7,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	// debug enables the in-container guest services (process execution and file
	// access) that back `ax ssh`. Off by default.
	Debug         bool `protobuf:"varint,10,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSpec) Reset() {
	*x = TaskSpec{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSpec) ProtoMessage() {}

func (x *TaskSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSpec.ProtoReflect.Descriptor instead.
func (*TaskSpec) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{2}
}

func (x *TaskSpec) GetSuspend() bool {
	if x != nil {
		return x.Suspend
	}
	return false
}

func (x *TaskSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *TaskSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TaskSpec) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TaskSpec) GetResources() *ResourceReqs {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *TaskSpec) GetWorkspaces() []*WorkspaceRef {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

func (x *TaskSpec) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{3}
}

func (x *EnvVar) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ResourceReqs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      *ResourceList          `protobuf:"bytes,1,opt,name=requests,proto3" json:"requests,omitempty"`
	Limits        *ResourceList          `protobuf:"bytes,2,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReqs) Reset() {
	*x = ResourceReqs{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReqs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReqs) ProtoMessage() {}

func (x *ResourceReqs) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReqs.ProtoReflect.Descriptor instead.
func (*ResourceReqs) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceReqs) GetRequests() *ResourceList {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ResourceReqs) GetLimits() *ResourceList {
	if x != nil {
		return x.Limits
	}
	return nil
}

type ResourceList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpu           string                 `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceList) Reset() {
	*x = ResourceList{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceList) ProtoMessage() {}

func (x *ResourceList) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceList.ProtoReflect.Descriptor instead.
func (*ResourceList) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceList) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *ResourceList) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type WorkspaceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Goal          string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceRef) Reset() {
	*x = WorkspaceRef{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceRef) ProtoMessage() {}

func (x *WorkspaceRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceRef.ProtoReflect.Descriptor instead.
func (*WorkspaceRef) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{6}
}

func (x *WorkspaceRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WorkspaceRef) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

type TaskStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Phase string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Id    string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Actor string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	// json_name keeps the established `workerIP` spelling in YAML and JSON.
	WorkerIp        string           `protobuf:"bytes,4,opt,name=worker_ip,json=workerIP,proto3" json:"worker_ip,omitempty"`
	PendingApproval *PendingApproval `protobuf:"bytes,5,opt,name=pending_approval,json=pendingApproval,proto3" json:"pending_approval,omitempty"`
	Usage           *UsageStats      `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	Conditions      []*Condition     `protobuf:"bytes,7,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{7}
}

func (x *TaskStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *TaskStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskStatus) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *TaskStatus) GetWorkerIp() string {
	if x != nil {
		return x.WorkerIp
	}
	return ""
}

func (x *TaskStatus) GetPendingApproval() *PendingApproval {
	if x != nil {
		return x.PendingApproval
	}
	return nil
}

func (x *TaskStatus) GetUsage() *UsageStats {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *TaskStatus) GetConditions() []*Condition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type PendingApproval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	RequestedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingApproval) Reset() {
	*x = PendingApproval{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingApproval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingApproval) ProtoMessage() {}

func (x *PendingApproval) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingApproval.ProtoReflect.Descriptor instead.
func (*PendingApproval) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{8}
}

func (x *PendingApproval) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PendingApproval) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PendingApproval) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

type UsageStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UsageStats) Reset() {
	*x = UsageStats{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageStats) ProtoMessage() {}

func (x *UsageStats) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageStats.ProtoReflect.Descriptor instead.
func (*UsageStats) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{9}
}

func (x *UsageStats) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *UsageStats) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

type Condition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	Reason             string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{10}
}

func (x *Condition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Condition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Condition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

func (x *Condition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Condition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Workspace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *ObjectMeta            `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *WorkspaceSpec         `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workspace) Reset() {
	*x = Workspace{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workspace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workspace) ProtoMessage() {}

func (x *Workspace) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workspace.ProtoReflect.Descriptor instead.
func (*Workspace) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{11}
}

func (x *Workspace) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Workspace) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Workspace) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Workspace) GetSpec() *WorkspaceSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type WorkspaceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Git           []*GitRepo             `protobuf:"bytes,1,rep,name=git,proto3" json:"git,omitempty"`
	Mcp           *MCPConfig             `protobuf:"bytes,2,opt,name=mcp,proto3" json:"mcp,omitempty"`
	Skills        *SkillsConfig          `protobuf:"bytes,3,opt,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceSpec) Reset() {
	*x = WorkspaceSpec{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceSpec) ProtoMessage() {}

func (x *WorkspaceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceSpec.ProtoReflect.Descriptor instead.
func (*WorkspaceSpec) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{12}
}

func (x *WorkspaceSpec) GetGit() []*GitRepo {
	if x != nil {
		return x.Git
	}
	return nil
}

func (x *WorkspaceSpec) GetMcp() *MCPConfig {
	if x != nil {
		return x.Mcp
	}
	return nil
}

func (x *WorkspaceSpec) GetSkills() *SkillsConfig {
	if x != nil {
		return x.Skills
	}
	return nil
}

type GitRepo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	Branch        string                 `protobuf:"bytes,3,opt,name=branch,proto3" json:"branch,omitempty"`
	Dir           string                 `protobuf:"bytes,4,opt,name=dir,proto3" json:"dir,omitempty"`
	Depth         int32                  `protobuf:"varint,5,opt,name=depth,proto3" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitRepo) Reset() {
	*x = GitRepo{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitRepo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitRepo) ProtoMessage() {}

func (x *GitRepo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitRepo.ProtoReflect.Descriptor instead.
func (*GitRepo) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{13}
}

func (x *GitRepo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GitRepo) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *GitRepo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *GitRepo) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *GitRepo) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

type MCPConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registries    []*MCPRegistry         `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	Servers       []*MCPServer           `protobuf:"bytes,2,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPConfig) Reset() {
	*x = MCPConfig{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPConfig) ProtoMessage() {}

func (x *MCPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPConfig.ProtoReflect.Descriptor instead.
func (*MCPConfig) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{14}
}

func (x *MCPConfig) GetRegistries() []*MCPRegistry {
	if x != nil {
		return x.Registries
	}
	return nil
}

func (x *MCPConfig) GetServers() []*MCPServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

type MCPRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Servers       []*MCPServer           `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPRegistry) Reset() {
	*x = MCPRegistry{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPRegistry) ProtoMessage() {}

func (x *MCPRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPRegistry.ProtoReflect.Descriptor instead.
func (*MCPRegistry) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{15}
}

func (x *MCPRegistry) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *MCPRegistry) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *MCPRegistry) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MCPRegistry) GetServers() []*MCPServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

type MCPServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoint      string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MCPServer) Reset() {
	*x = MCPServer{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MCPServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MCPServer) ProtoMessage() {}

func (x *MCPServer) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MCPServer.ProtoReflect.Descriptor instead.
func (*MCPServer) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{16}
}

func (x *MCPServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MCPServer) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MCPServer) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *MCPServer) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type SkillsConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registries    []*SkillRegistry       `protobuf:"bytes,1,rep,name=registries,proto3" json:"registries,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillsConfig) Reset() {
	*x = SkillsConfig{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillsConfig) ProtoMessage() {}

func (x *SkillsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillsConfig.ProtoReflect.Descriptor instead.
func (*SkillsConfig) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{17}
}

func (x *SkillsConfig) GetRegistries() []*SkillRegistry {
	if x != nil {
		return x.Registries
	}
	return nil
}

func (x *SkillsConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SkillRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Project       string                 `protobuf:"bytes,2,opt,name=project,proto3" json:"project,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillRegistry) Reset() {
	*x = SkillRegistry{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillRegistry) ProtoMessage() {}

func (x *SkillRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillRegistry.ProtoReflect.Descriptor instead.
func (*SkillRegistry) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{18}
}

func (x *SkillRegistry) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SkillRegistry) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SkillRegistry) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    string                 `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Metadata      *ObjectMeta            `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *ModelSpec             `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{19}
}

func (x *Model) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *Model) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Model) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Model) GetSpec() *ModelSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ModelSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Provider  string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Model     string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SecretKey *SecretKeyRef          `protobuf:"bytes,6,opt,name=secret_key,json=secretKey,proto3" json:"secret_key,omitempty"`
	// parameters are provider-specific generation settings passed through to the
	// model API as-is, for example temperature or maxOutputTokens for Gemini.
	Parameters *structpb.Struct `protobuf:"bytes,7,opt,name=parameters,proto3" json:"parameters,omitempty"`
	// base_url is the provider endpoint base (scheme, host, optional port and
	// path prefix such as /v1) used instead of the provider default, so
	// self-hosted and gateway endpoints are declarable. json_name keeps the
	// `baseURL` spelling in YAML and JSON.
	BaseUrl string `protobuf:"bytes,8,opt,name=base_url,json=baseURL,proto3" json:"base_url,omitempty"`
	// api is the wire protocol the endpoint speaks. It is what lets a Model reach
	// an endpoint whose protocol differs from its provider family: an
	// OpenAI-compatible service that only implements the Responses API, or an
	// Anthropic-compatible gateway in front of another vendor. Unset means the
	// provider default: google-generate-content for google, openai-completions
	// for openai, anthropic-messages for anthropic.
	Api           string `protobuf:"bytes,9,opt,name=api,proto3" json:"api,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelSpec) Reset() {
	*x = ModelSpec{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelSpec) ProtoMessage() {}

func (x *ModelSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelSpec.ProtoReflect.Descriptor instead.
func (*ModelSpec) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{20}
}

func (x *ModelSpec) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelSpec) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelSpec) GetSecretKey() *SecretKeyRef {
	if x != nil {
		return x.SecretKey
	}
	return nil
}

func (x *ModelSpec) GetParameters() *structpb.Struct {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *ModelSpec) GetBaseUrl() string {
	if x != nil {
		return x.BaseUrl
	}
	return ""
}

func (x *ModelSpec) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

type SecretKeyRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretKeyRef) Reset() {
	*x = SecretKeyRef{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretKeyRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretKeyRef) ProtoMessage() {}

func (x *SecretKeyRef) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretKeyRef.ProtoReflect.Descriptor instead.
func (*SecretKeyRef) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{21}
}

func (x *SecretKeyRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretKeyRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Tasks
type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{22}
}

func (x *GetTaskRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *GetTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{23}
}

func (x *ListTasksRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{24}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteTaskRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *DeleteTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{27}
}

type SuspendTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuspendTaskRequest) Reset() {
	*x = SuspendTaskRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuspendTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspendTaskRequest) ProtoMessage() {}

func (x *SuspendTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspendTaskRequest.ProtoReflect.Descriptor instead.
func (*SuspendTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{28}
}

func (x *SuspendTaskRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *SuspendTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResumeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTaskRequest) Reset() {
	*x = ResumeTaskRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTaskRequest) ProtoMessage() {}

func (x *ResumeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTaskRequest.ProtoReflect.Descriptor instead.
func (*ResumeTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{29}
}

func (x *ResumeTaskRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *ResumeTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WatchTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTaskRequest) Reset() {
	*x = WatchTaskRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTaskRequest) ProtoMessage() {}

func (x *WatchTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTaskRequest.ProtoReflect.Descriptor instead.
func (*WatchTaskRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{30}
}

func (x *WatchTaskRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *WatchTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WatchTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTaskResponse) Reset() {
	*x = WatchTaskResponse{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTaskResponse) ProtoMessage() {}

func (x *WatchTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTaskResponse.ProtoReflect.Descriptor instead.
func (*WatchTaskResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{31}
}

func (x *WatchTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *WatchTaskResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// Workspaces
type GetWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkspaceRequest) Reset() {
	*x = GetWorkspaceRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkspaceRequest) ProtoMessage() {}

func (x *GetWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*GetWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{32}
}

func (x *GetWorkspaceRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *GetWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListWorkspacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesRequest) Reset() {
	*x = ListWorkspacesRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesRequest) ProtoMessage() {}

func (x *ListWorkspacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesRequest.ProtoReflect.Descriptor instead.
func (*ListWorkspacesRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{33}
}

func (x *ListWorkspacesRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

type ListWorkspacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspaces    []*Workspace           `protobuf:"bytes,1,rep,name=workspaces,proto3" json:"workspaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkspacesResponse) Reset() {
	*x = ListWorkspacesResponse{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkspacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkspacesResponse) ProtoMessage() {}

func (x *ListWorkspacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkspacesResponse.ProtoReflect.Descriptor instead.
func (*ListWorkspacesResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{34}
}

func (x *ListWorkspacesResponse) GetWorkspaces() []*Workspace {
	if x != nil {
		return x.Workspaces
	}
	return nil
}

type UpdateWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workspace     *Workspace             `protobuf:"bytes,1,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateWorkspaceRequest) Reset() {
	*x = UpdateWorkspaceRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWorkspaceRequest) ProtoMessage() {}

func (x *UpdateWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateWorkspaceRequest) GetWorkspace() *Workspace {
	if x != nil {
		return x.Workspace
	}
	return nil
}

type DeleteWorkspaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceRequest) Reset() {
	*x = DeleteWorkspaceRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceRequest) ProtoMessage() {}

func (x *DeleteWorkspaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{36}
}

func (x *DeleteWorkspaceRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *DeleteWorkspaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteWorkspaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkspaceResponse) Reset() {
	*x = DeleteWorkspaceResponse{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkspaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkspaceResponse) ProtoMessage() {}

func (x *DeleteWorkspaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkspaceResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkspaceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{37}
}

// Models
type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{38}
}

func (x *GetModelRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *GetModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{39}
}

func (x *ListModelsRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*Model               `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{40}
}

func (x *ListModelsResponse) GetModels() []*Model {
	if x != nil {
		return x.Models
	}
	return nil
}

type UpdateModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *Model                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateModelRequest) Reset() {
	*x = UpdateModelRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateModelRequest) ProtoMessage() {}

func (x *UpdateModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateModelRequest.ProtoReflect.Descriptor instead.
func (*UpdateModelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{41}
}

func (x *UpdateModelRequest) GetModel() *Model {
	if x != nil {
		return x.Model
	}
	return nil
}

type DeleteModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Atespace      string                 `protobuf:"bytes,1,opt,name=atespace,proto3" json:"atespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelRequest) Reset() {
	*x = DeleteModelRequest{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelRequest) ProtoMessage() {}

func (x *DeleteModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelRequest.ProtoReflect.Descriptor instead.
func (*DeleteModelRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{42}
}

func (x *DeleteModelRequest) GetAtespace() string {
	if x != nil {
		return x.Atespace
	}
	return ""
}

func (x *DeleteModelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteModelResponse) Reset() {
	*x = DeleteModelResponse{}
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteModelResponse) ProtoMessage() {}

func (x *DeleteModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_v1alpha1_ax_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteModelResponse.ProtoReflect.Descriptor instead.
func (*DeleteModelResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP(), []int{43}
}

var File_pkg_apis_v1alpha1_ax_proto protoreflect.FileDescriptor

const file_pkg_apis_v1alpha1_ax_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/apis/v1alpha1/ax.proto\x12\vax.v1alpha1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x87\x01\n" +
	"\n" +
	"ObjectMeta\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\batespace\x18\x02 \x01(\tR\batespace\x12I\n" +
	"\x12creation_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x11creationTimestamp\"\xcc\x01\n" +
	"\x04Task\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.ax.v1alpha1.ObjectMetaR\bmetadata\x12)\n" +
	"\x04spec\x18\x04 \x01(\v2\x15.ax.v1alpha1.TaskSpecR\x04spec\x12/\n" +
	"\x06status\x18\x05 \x01(\v2\x17.ax.v1alpha1.TaskStatusR\x06status\"\xb0\x02\n" +
	"\bTaskSpec\x12\x18\n" +
	"\asuspend\x18\x02 \x01(\bR\asuspend\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12%\n" +
	"\x03env\x18\x05 \x03(\v2\x13.ax.v1alpha1.EnvVarR\x03env\x127\n" +
	"\tresources\x18\x06 \x01(\v2\x19.ax.v1alpha1.ResourceReqsR\tresources\x129\n" +
	"\n" +
	"workspaces\x18\a \x03(\v2\x19.ax.v1alpha1.WorkspaceRefR\n" +
	"workspaces\x12\x14\n" +
	"\x05debug\x18\n" +
	" \x01(\bR\x05debugJ\x04\b\x01\x10\x02J\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"R\x04goalR\agatewayR\bpolicies\"2\n" +
	"\x06EnvVar\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"x\n" +
	"\fResourceReqs\x125\n" +
	"\brequests\x18\x01 \x01(\v2\x19.ax.v1alpha1.ResourceListR\brequests\x121\n" +
	"\x06limits\x18\x02 \x01(\v2\x19.ax.v1alpha1.ResourceListR\x06limits\"8\n" +
	"\fResourceList\x12\x10\n" +
	"\x03cpu\x18\x01 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x02 \x01(\tR\x06memory\"J\n" +
	"\fWorkspaceRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\"\x95\x02\n" +
	"\n" +
	"TaskStatus\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x1b\n" +
	"\tworker_ip\x18\x04 \x01(\tR\bworkerIP\x12G\n" +
	"\x10pending_approval\x18\x05 \x01(\v2\x1c.ax.v1alpha1.PendingApprovalR\x0fpendingApproval\x12-\n" +
	"\x05usage\x18\x06 \x01(\v2\x17.ax.v1alpha1.UsageStatsR\x05usage\x126\n" +
	"\n" +
	"conditions\x18\a \x03(\v2\x16.ax.v1alpha1.ConditionR\n" +
	"conditions\"x\n" +
	"\x0fPendingApproval\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12=\n" +
	"\frequested_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"^\n" +
	"\n" +
	"UsageStats\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\"\xb7\x01\n" +
	"\tCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12L\n" +
	"\x14last_transition_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastTransitionTime\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\xa5\x01\n" +
	"\tWorkspace\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.ax.v1alpha1.ObjectMetaR\bmetadata\x12.\n" +
	"\x04spec\x18\x04 \x01(\v2\x1a.ax.v1alpha1.WorkspaceSpecR\x04spec\"\x94\x01\n" +
	"\rWorkspaceSpec\x12&\n" +
	"\x03git\x18\x01 \x03(\v2\x14.ax.v1alpha1.GitRepoR\x03git\x12(\n" +
	"\x03mcp\x18\x02 \x01(\v2\x16.ax.v1alpha1.MCPConfigR\x03mcp\x121\n" +
	"\x06skills\x18\x03 \x01(\v2\x19.ax.v1alpha1.SkillsConfigR\x06skills\"q\n" +
	"\aGitRepo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\x12\x16\n" +
	"\x06branch\x18\x03 \x01(\tR\x06branch\x12\x10\n" +
	"\x03dir\x18\x04 \x01(\tR\x03dir\x12\x14\n" +
	"\x05depth\x18\x05 \x01(\x05R\x05depth\"w\n" +
	"\tMCPConfig\x128\n" +
	"\n" +
	"registries\x18\x01 \x03(\v2\x18.ax.v1alpha1.MCPRegistryR\n" +
	"registries\x120\n" +
	"\aservers\x18\x02 \x03(\v2\x16.ax.v1alpha1.MCPServerR\aservers\"\x8b\x01\n" +
	"\vMCPRegistry\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x120\n" +
	"\aservers\x18\x04 \x03(\v2\x16.ax.v1alpha1.MCPServerR\aservers\"i\n" +
	"\tMCPServer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\"^\n" +
	"\fSkillsConfig\x12:\n" +
	"\n" +
	"registries\x18\x01 \x03(\v2\x1a.ax.v1alpha1.SkillRegistryR\n" +
	"registries\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"[\n" +
	"\rSkillRegistry\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x18\n" +
	"\aproject\x18\x02 \x01(\tR\aproject\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\"\x9d\x01\n" +
	"\x05Model\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.ax.v1alpha1.ObjectMetaR\bmetadata\x12*\n" +
	"\x04spec\x18\x04 \x01(\v2\x16.ax.v1alpha1.ModelSpecR\x04spec\"\x9c\x02\n" +
	"\tModelSpec\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x128\n" +
	"\n" +
	"secret_key\x18\x06 \x01(\v2\x19.ax.v1alpha1.SecretKeyRefR\tsecretKey\x127\n" +
	"\n" +
	"parameters\x18\a \x01(\v2\x17.google.protobuf.StructR\n" +
	"parameters\x12\x19\n" +
	"\bbase_url\x18\b \x01(\tR\abaseURL\x12\x10\n" +
	"\x03api\x18\t \x01(\tR\x03apiJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05J\x04\b\x05\x10\x06R\vtemperatureR\n" +
	"max_tokensR\x12system_instruction\"4\n" +
	"\fSecretKeyRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"@\n" +
	"\x0eGetTaskRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\\\n" +
	"\x10ListTasksRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\"<\n" +
	"\x11ListTasksResponse\x12'\n" +
	"\x05tasks\x18\x01 \x03(\v2\x11.ax.v1alpha1.TaskR\x05tasks\":\n" +
	"\x11UpdateTaskRequest\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.ax.v1alpha1.TaskR\x04task\"C\n" +
	"\x11DeleteTaskRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x14\n" +
	"\x12DeleteTaskResponse\"D\n" +
	"\x12SuspendTaskRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"C\n" +
	"\x11ResumeTaskRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"B\n" +
	"\x10WatchTaskRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"R\n" +
	"\x11WatchTaskResponse\x12%\n" +
	"\x04task\x18\x01 \x01(\v2\x11.ax.v1alpha1.TaskR\x04task\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"E\n" +
	"\x13GetWorkspaceRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"3\n" +
	"\x15ListWorkspacesRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\"P\n" +
	"\x16ListWorkspacesResponse\x126\n" +
	"\n" +
	"workspaces\x18\x01 \x03(\v2\x16.ax.v1alpha1.WorkspaceR\n" +
	"workspaces\"N\n" +
	"\x16UpdateWorkspaceRequest\x124\n" +
	"\tworkspace\x18\x01 \x01(\v2\x16.ax.v1alpha1.WorkspaceR\tworkspace\"H\n" +
	"\x16DeleteWorkspaceRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x19\n" +
	"\x17DeleteWorkspaceResponse\"A\n" +
	"\x0fGetModelRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\x11ListModelsRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\"@\n" +
	"\x12ListModelsResponse\x12*\n" +
	"\x06models\x18\x01 \x03(\v2\x12.ax.v1alpha1.ModelR\x06models\">\n" +
	"\x12UpdateModelRequest\x12(\n" +
	"\x05model\x18\x01 \x01(\v2\x12.ax.v1alpha1.ModelR\x05model\"D\n" +
	"\x12DeleteModelRequest\x12\x1a\n" +
	"\batespace\x18\x01 \x01(\tR\batespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x15\n" +
	"\x13DeleteModelResponse2\xe3\b\n" +
	"\x02AX\x129\n" +
	"\aGetTask\x12\x1b.ax.v1alpha1.GetTaskRequest\x1a\x11.ax.v1alpha1.Task\x12J\n" +
	"\tListTasks\x12\x1d.ax.v1alpha1.ListTasksRequest\x1a\x1e.ax.v1alpha1.ListTasksResponse\x12?\n" +
	"\n" +
	"UpdateTask\x12\x1e.ax.v1alpha1.UpdateTaskRequest\x1a\x11.ax.v1alpha1.Task\x12M\n" +
	"\n" +
	"DeleteTask\x12\x1e.ax.v1alpha1.DeleteTaskRequest\x1a\x1f.ax.v1alpha1.DeleteTaskResponse\x12A\n" +
	"\vSuspendTask\x12\x1f.ax.v1alpha1.SuspendTaskRequest\x1a\x11.ax.v1alpha1.Task\x12?\n" +
	"\n" +
	"ResumeTask\x12\x1e.ax.v1alpha1.ResumeTaskRequest\x1a\x11.ax.v1alpha1.Task\x12L\n" +
	"\tWatchTask\x12\x1d.ax.v1alpha1.WatchTaskRequest\x1a\x1e.ax.v1alpha1.WatchTaskResponse0\x01\x12H\n" +
	"\fGetWorkspace\x12 .ax.v1alpha1.GetWorkspaceRequest\x1a\x16.ax.v1alpha1.Workspace\x12Y\n" +
	"\x0eListWorkspaces\x12\".ax.v1alpha1.ListWorkspacesRequest\x1a#.ax.v1alpha1.ListWorkspacesResponse\x12N\n" +
	"\x0fUpdateWorkspace\x12#.ax.v1alpha1.UpdateWorkspaceRequest\x1a\x16.ax.v1alpha1.Workspace\x12\\\n" +
	"\x0fDeleteWorkspace\x12#.ax.v1alpha1.DeleteWorkspaceRequest\x1a$.ax.v1alpha1.DeleteWorkspaceResponse\x12<\n" +
	"\bGetModel\x12\x1c.ax.v1alpha1.GetModelRequest\x1a\x12.ax.v1alpha1.Model\x12M\n" +
	"\n" +
	"ListModels\x12\x1e.ax.v1alpha1.ListModelsRequest\x1a\x1f.ax.v1alpha1.ListModelsResponse\x12B\n" +
	"\vUpdateModel\x12\x1f.ax.v1alpha1.UpdateModelRequest\x1a\x12.ax.v1alpha1.Model\x12P\n" +
	"\vDeleteModel\x12\x1f.ax.v1alpha1.DeleteModelRequest\x1a .ax.v1alpha1.DeleteModelResponseB(Z&github.com/google/ax/pkg/apis/v1alpha1b\x06proto3"

var (
	file_pkg_apis_v1alpha1_ax_proto_rawDescOnce sync.Once
	file_pkg_apis_v1alpha1_ax_proto_rawDescData []byte
)

func file_pkg_apis_v1alpha1_ax_proto_rawDescGZIP() []byte {
	file_pkg_apis_v1alpha1_ax_proto_rawDescOnce.Do(func() {
		file_pkg_apis_v1alpha1_ax_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apis_v1alpha1_ax_proto_rawDesc), len(file_pkg_apis_v1alpha1_ax_proto_rawDesc)))
	})
	return file_pkg_apis_v1alpha1_ax_proto_rawDescData
}

var file_pkg_apis_v1alpha1_ax_proto_msgTypes = make([]protoimpl.MessageInfo, 44)
var file_pkg_apis_v1alpha1_ax_proto_goTypes = []any{
	(*ObjectMeta)(nil),              // 0: ax.v1alpha1.ObjectMeta
	(*Task)(nil),                    // 1: ax.v1alpha1.Task
	(*TaskSpec)(nil),                // 2: ax.v1alpha1.TaskSpec
	(*EnvVar)(nil),                  // 3: ax.v1alpha1.EnvVar
	(*ResourceReqs)(nil),            // 4: ax.v1alpha1.ResourceReqs
	(*ResourceList)(nil),            // 5: ax.v1alpha1.ResourceList
	(*WorkspaceRef)(nil),            // 6: ax.v1alpha1.WorkspaceRef
	(*TaskStatus)(nil),              // 7: ax.v1alpha1.TaskStatus
	(*PendingApproval)(nil),         // 8: ax.v1alpha1.PendingApproval
	(*UsageStats)(nil),              // 9: ax.v1alpha1.UsageStats
	(*Condition)(nil),               // 10: ax.v1alpha1.Condition
	(*Workspace)(nil),               // 11: ax.v1alpha1.Workspace
	(*WorkspaceSpec)(nil),           // 12: ax.v1alpha1.WorkspaceSpec
	(*GitRepo)(nil),                 // 13: ax.v1alpha1.GitRepo
	(*MCPConfig)(nil),               // 14: ax.v1alpha1.MCPConfig
	(*MCPRegistry)(nil),             // 15: ax.v1alpha1.MCPRegistry
	(*MCPServer)(nil),               // 16: ax.v1alpha1.MCPServer
	(*SkillsConfig)(nil),            // 17: ax.v1alpha1.SkillsConfig
	(*SkillRegistry)(nil),           // 18: ax.v1alpha1.SkillRegistry
	(*Model)(nil),                   // 19: ax.v1alpha1.Model
	(*ModelSpec)(nil),               // 20: ax.v1alpha1.ModelSpec
	(*SecretKeyRef)(nil),            // 21: ax.v1alpha1.SecretKeyRef
	(*GetTaskRequest)(nil),          // 22: ax.v1alpha1.GetTaskRequest
	(*ListTasksRequest)(nil),        // 23: ax.v1alpha1.ListTasksRequest
	(*ListTasksResponse)(nil),       // 24: ax.v1alpha1.ListTasksResponse
	(*UpdateTaskRequest)(nil),       // 25: ax.v1alpha1.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),       // 26: ax.v1alpha1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),      // 27: ax.v1alpha1.DeleteTaskResponse
	(*SuspendTaskRequest)(nil),      // 28: ax.v1alpha1.SuspendTaskRequest
	(*ResumeTaskRequest)(nil),       // 29: ax.v1alpha1.ResumeTaskRequest
	(*WatchTaskRequest)(nil),        // 30: ax.v1alpha1.WatchTaskRequest
	(*WatchTaskResponse)(nil),       // 31: ax.v1alpha1.WatchTaskResponse
	(*GetWorkspaceRequest)(nil),     // 32: ax.v1alpha1.GetWorkspaceRequest
	(*ListWorkspacesRequest)(nil),   // 33: ax.v1alpha1.ListWorkspacesRequest
	(*ListWorkspacesResponse)(nil),  // 34: ax.v1alpha1.ListWorkspacesResponse
	(*UpdateWorkspaceRequest)(nil),  // 35: ax.v1alpha1.UpdateWorkspaceRequest
	(*DeleteWorkspaceRequest)(nil),  // 36: ax.v1alpha1.DeleteWorkspaceRequest
	(*DeleteWorkspaceResponse)(nil), // 37: ax.v1alpha1.DeleteWorkspaceResponse
	(*GetModelRequest)(nil),         // 38: ax.v1alpha1.GetModelRequest
	(*ListModelsRequest)(nil),       // 39: ax.v1alpha1.ListModelsRequest
	(*ListModelsResponse)(nil),      // 40: ax.v1alpha1.ListModelsResponse
	(*UpdateModelRequest)(nil),      // 41: ax.v1alpha1.UpdateModelRequest
	(*DeleteModelRequest)(nil),      // 42: ax.v1alpha1.DeleteModelRequest
	(*DeleteModelResponse)(nil),     // 43: ax.v1alpha1.DeleteModelResponse
	(*timestamppb.Timestamp)(nil),   // 44: google.protobuf.Timestamp
	(*structpb.Struct)(nil),         // 45: google.protobuf.Struct
}
var file_pkg_apis_v1alpha1_ax_proto_depIdxs = []int32{
	44, // 0: ax.v1alpha1.ObjectMeta.creation_timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: ax.v1alpha1.Task.metadata:type_name -> ax.v1alpha1.ObjectMeta
	2,  // 2: ax.v1alpha1.Task.spec:type_name -> ax.v1alpha1.TaskSpec
	7,  // 3: ax.v1alpha1.Task.status:type_name -> ax.v1alpha1.TaskStatus
	3,  // 4: ax.v1alpha1.TaskSpec.env:type_name -> ax.v1alpha1.EnvVar
	4,  // 5: ax.v1alpha1.TaskSpec.resources:type_name -> ax.v1alpha1.ResourceReqs
	6,  // 6: ax.v1alpha1.TaskSpec.workspaces:type_name -> ax.v1alpha1.WorkspaceRef
	5,  // 7: ax.v1alpha1.ResourceReqs.requests:type_name -> ax.v1alpha1.ResourceList
	5,  // 8: ax.v1alpha1.ResourceReqs.limits:type_name -> ax.v1alpha1.ResourceList
	8,  // 9: ax.v1alpha1.TaskStatus.pending_approval:type_name -> ax.v1alpha1.PendingApproval
	9,  // 10: ax.v1alpha1.TaskStatus.usage:type_name -> ax.v1alpha1.UsageStats
	10, // 11: ax.v1alpha1.TaskStatus.conditions:type_name -> ax.v1alpha1.Condition
	44, // 12: ax.v1alpha1.PendingApproval.requested_at:type_name -> google.protobuf.Timestamp
	44, // 13: ax.v1alpha1.Condition.last_transition_time:type_name -> google.protobuf.Timestamp
	0,  // 14: ax.v1alpha1.Workspace.metadata:type_name -> ax.v1alpha1.ObjectMeta
	12, // 15: ax.v1alpha1.Workspace.spec:type_name -> ax.v1alpha1.WorkspaceSpec
	13, // 16: ax.v1alpha1.WorkspaceSpec.git:type_name -> ax.v1alpha1.GitRepo
	14, // 17: ax.v1alpha1.WorkspaceSpec.mcp:type_name -> ax.v1alpha1.MCPConfig
	17, // 18: ax.v1alpha1.WorkspaceSpec.skills:type_name -> ax.v1alpha1.SkillsConfig
	15, // 19: ax.v1alpha1.MCPConfig.registries:type_name -> ax.v1alpha1.MCPRegistry
	16, // 20: ax.v1alpha1.MCPConfig.servers:type_name -> ax.v1alpha1.MCPServer
	16, // 21: ax.v1alpha1.MCPRegistry.servers:type_name -> ax.v1alpha1.MCPServer
	18, // 22: ax.v1alpha1.SkillsConfig.registries:type_name -> ax.v1alpha1.SkillRegistry
	0,  // 23: ax.v1alpha1.Model.metadata:type_name -> ax.v1alpha1.ObjectMeta
	20, // 24: ax.v1alpha1.Model.spec:type_name -> ax.v1alpha1.ModelSpec
	21, // 25: ax.v1alpha1.ModelSpec.secret_key:type_name -> ax.v1alpha1.SecretKeyRef
	45, // 26: ax.v1alpha1.ModelSpec.parameters:type_name -> google.protobuf.Struct
	1,  // 27: ax.v1alpha1.ListTasksResponse.tasks:type_name -> ax.v1alpha1.Task
	1,  // 28: ax.v1alpha1.UpdateTaskRequest.task:type_name -> ax.v1alpha1.Task
	1,  // 29: ax.v1alpha1.WatchTaskResponse.task:type_name -> ax.v1alpha1.Task
	11, // 30: ax.v1alpha1.ListWorkspacesResponse.workspaces:type_name -> ax.v1alpha1.Workspace
	11, // 31: ax.v1alpha1.UpdateWorkspaceRequest.workspace:type_name -> ax.v1alpha1.Workspace
	19, // 32: ax.v1alpha1.ListModelsResponse.models:type_name -> ax.v1alpha1.Model
	19, // 33: ax.v1alpha1.UpdateModelRequest.model:type_name -> ax.v1alpha1.Model
	22, // 34: ax.v1alpha1.AX.GetTask:input_type -> ax.v1alpha1.GetTaskRequest
	23, // 35: ax.v1alpha1.AX.ListTasks:input_type -> ax.v1alpha1.ListTasksRequest
	25, // 36: ax.v1alpha1.AX.UpdateTask:input_type -> ax.v1alpha1.UpdateTaskRequest
	26, // 37: ax.v1alpha1.AX.DeleteTask:input_type -> ax.v1alpha1.DeleteTaskRequest
	28, // 38: ax.v1alpha1.AX.SuspendTask:input_type -> ax.v1alpha1.SuspendTaskRequest
	29, // 39: ax.v1alpha1.AX.ResumeTask:input_type -> ax.v1alpha1.ResumeTaskRequest
	30, // 40: ax.v1alpha1.AX.WatchTask:input_type -> ax.v1alpha1.WatchTaskRequest
	32, // 41: ax.v1alpha1.AX.GetWorkspace:input_type -> ax.v1alpha1.GetWorkspaceRequest
	33, // 42: ax.v1alpha1.AX.ListWorkspaces:input_type -> ax.v1alpha1.ListWorkspacesRequest
	35, // 43: ax.v1alpha1.AX.UpdateWorkspace:input_type -> ax.v1alpha1.UpdateWorkspaceRequest
	36, // 44: ax.v1alpha1.AX.DeleteWorkspace:input_type -> ax.v1alpha1.DeleteWorkspaceRequest
	38, // 45: ax.v1alpha1.AX.GetModel:input_type -> ax.v1alpha1.GetModelRequest
	39, // 46: ax.v1alpha1.AX.ListModels:input_type -> ax.v1alpha1.ListModelsRequest
	41, // 47: ax.v1alpha1.AX.UpdateModel:input_type -> ax.v1alpha1.UpdateModelRequest
	42, // 48: ax.v1alpha1.AX.DeleteModel:input_type -> ax.v1alpha1.DeleteModelRequest
	1,  // 49: ax.v1alpha1.AX.GetTask:output_type -> ax.v1alpha1.Task
	24, // 50: ax.v1alpha1.AX.ListTasks:output_type -> ax.v1alpha1.ListTasksResponse
	1,  // 51: ax.v1alpha1.AX.UpdateTask:output_type -> ax.v1alpha1.Task
	27, // 52: ax.v1alpha1.AX.DeleteTask:output_type -> ax.v1alpha1.DeleteTaskResponse
	1,  // 53: ax.v1alpha1.AX.SuspendTask:output_type -> ax.v1alpha1.Task
	1,  // 54: ax.v1alpha1.AX.ResumeTask:output_type -> ax.v1alpha1.Task
	31, // 55: ax.v1alpha1.AX.WatchTask:output_type -> ax.v1alpha1.WatchTaskResponse
	11, // 56: ax.v1alpha1.AX.GetWorkspace:output_type -> ax.v1alpha1.Workspace
	34, // 57: ax.v1alpha1.AX.ListWorkspaces:output_type -> ax.v1alpha1.ListWorkspacesResponse
	11, // 58: ax.v1alpha1.AX.UpdateWorkspace:output_type -> ax.v1alpha1.Workspace
	37, // 59: ax.v1alpha1.AX.DeleteWorkspace:output_type -> ax.v1alpha1.DeleteWorkspaceResponse
	19, // 60: ax.v1alpha1.AX.GetModel:output_type -> ax.v1alpha1.Model
	40, // 61: ax.v1alpha1.AX.ListModels:output_type -> ax.v1alpha1.ListModelsResponse
	19, // 62: ax.v1alpha1.AX.UpdateModel:output_type -> ax.v1alpha1.Model
	43, // 63: ax.v1alpha1.AX.DeleteModel:output_type -> ax.v1alpha1.DeleteModelResponse
	49, // [49:64] is the sub-list for method output_type
	34, // [34:49] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_pkg_apis_v1alpha1_ax_proto_init() }
func file_pkg_apis_v1alpha1_ax_proto_init() {
	if File_pkg_apis_v1alpha1_ax_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apis_v1alpha1_ax_proto_rawDesc), len(file_pkg_apis_v1alpha1_ax_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   44,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_v1alpha1_ax_proto_goTypes,
		DependencyIndexes: file_pkg_apis_v1alpha1_ax_proto_depIdxs,
		MessageInfos:      file_pkg_apis_v1alpha1_ax_proto_msgTypes,
	}.Build()
	File_pkg_apis_v1alpha1_ax_proto = out.File
	file_pkg_apis_v1alpha1_ax_proto_goTypes = nil
	file_pkg_apis_v1alpha1_ax_proto_depIdxs = nil
}
